###########################################################################################
###########################################################################################
############################### FRONT

test:
  path:
    fr: test
  controller: App\Controller\Front\ContactController:editCandidature

ajax/set-locale:
  path: ajax/set-locale
  controller: App\Controller\FrontController:ajaxSetLocale
  options:
    expose: true


##########################################################
################# HOME
index:
  path: /
  controller: App\Controller\Front\HomeController::home

##########################################################
################# USER

login:
  path: identification
  controller: App\Controller\Front\UserController:login

logout:
  path: deconnexion


register:
  path: inscription
  controller: App\Controller\Front\UserController:register

##########################################################
################# KEYWORD

keywords:
  path: keywords
  controller: App\Controller\Backoffice\KeywordController:listKeyword

keyword/edit:
  path: keyword/{id}/edit
  controller: App\Controller\Backoffice\KeywordController:editKeyword
  defaults:
    id: 0
  requirements:
    id: '[0-9]+'

keyword/delete:
  path: keyword/{id}/delete
  controller: App\Controller\Backoffice\KeywordController:deleteKeyword
  defaults:
    id: 0
  requirements:
    id: '[0-9]+'

keyword/requestKeyword:
      path: keyword/{id}/request
      controller: App\Controller\Backoffice\KeywordController:requestKeyword
      defaults:
        id: 0
      requirements:
        id: '[0-9]+'

##########################################################
################# TRENDS
trends:
  path: trends
  controller: App\Controller\Backoffice\TrendsController:getTrends
  defaults:
    id: 0
  requirements:
    id: '[0-9]+'

trends/visualize:
  path: trends/{name}/visualize
  controller: App\Controller\Backoffice\TrendsController:visualizeTrend
  defaults:
    id: 0
  requirements:
    id: '[0-9]+'

##########################################################
################# TWITTER

front/twitter:
  path: /twitter
  controller: App\Controller\Front\TwitterController:showTweets
  defaults:
    id: 0
    requirements:
      id: '[0-9]+'

##########################################################
################# CUSTOMERS

###################
###CUSTOMERS DETAILS
front/customers-details:
  path: /customers/{slug}
  controller: App\Controller\Front\CustomerController:readCustomerDetails
  defaults:
    id: 0
    requirements:
      id: '[0-9]+'

###################
###REALISATIONS
front/realisations:
  path: /realisations
  controller: App\Controller\Front\CustomerController:readRealisation

###################
###REALISATIONS
front/realisation-filtre:
  path: /realisations-filtre
  controller: App\Controller\Front\CustomerController:filtreExpertiseAjax



###########################################################################################
###########################################################################################
############################### BACKOFFICE

##########################################################
################# COMMON

backoffice/ajax-edit:
  path: backoffice/ajax-edit
  controller: App\Controller\Backoffice\BackofficeController:ajaxEdit
  options:
    expose: true

backoffice/ajax-sort:
  path: backoffice/ajax-sort
  controller: App\Controller\Backoffice\BackofficeController:ajaxSort
  options:
    expose: true

backoffice/ajax-upload-media:
  path: backoffice/ajax-upload-media
  controller: App\Controller\Backoffice\BackofficeController:ajaxUploadMedia
  options:
    expose: true

backoffice/ajax-delete-file:
  path: backoffice/ajax-delete-file
  controller: App\Controller\Backoffice\BackofficeController:ajaxDeleteFile
  options:
    expose: true

backoffice/ajax-toggle-unique:
  path: backoffice/ajax-toggle-unique
  controller: App\Controller\Backoffice\BackofficeController:ajaxToggleUnique
  options:
    expose: true



##########################################################
################# DASHBOARD

backoffice/dashboard:
  path: backoffice
  controller: App\Controller\Backoffice\DashboardController:dashboard


##########################################################
################# CONFIGURATION

backoffice/config/languages:
  path: backoffice/config/languages
  controller: App\Controller\Backoffice\LanguageController:list

backoffice/config/language/edit:
  path: backoffice/config/language/{id}/edit
  controller: App\Controller\Backoffice\LanguageController:edit
  defaults:
    id: 0
  requirements:
    id: '[0-9]+'

##########################################################
################# USER

backoffice/users:
  path: backoffice/users
  controller: App\Controller\Backoffice\UserController:listUser

backoffice/user/edit:
  path: backoffice/user/{id}/edit
  controller: App\Controller\Backoffice\UserController:editUser
  defaults:
    id: 0
  requirements:
    id: '[0-9]+'

backoffice/user/change-password:
  path: backoffice/user/{id}/change-password
  controller: App\Controller\Backoffice\UserController:changePassword
  requirements:
    id: '[0-9]+'

##########################################################
################# OPTIN

backoffice/user/optins:
  path: backoffice/user/optins
  controller: App\Controller\Backoffice\User\OptinController:list

backoffice/user/optin/delete:
  path: backoffice/user/optin/{id}/delete/
  controller: App\Controller\Backoffice\User\OptinController:delete
  requirements:
    id: '[0-9]+'

##########################################################
################# CUSTOMMER / TRUSTED CUSTOMMER / EXPERTISE

###################
### CUSTOMER
backoffice/customers:
  path: backoffice/customers
  controller: App\Controller\Backoffice\CustomerController:listCustomer

backoffice/customer/edit:
  path: backoffice/customer/{id}/edit
  controller: App\Controller\Backoffice\CustomerController:editCustomer
  defaults:
    id: 0
  requirements:
    id: '[0-9]+'

backoffice/customer/delete:
  path: backoffice/customer/{id}/delete
  controller: App\Controller\Backoffice\CustomerController:deleteCustomer
  defaults:
    id: 0
  requirements:
    id: '[0-9]+'

    

